-- SQL Generated by Parser
INSERT IGNORE INTO questions (statement, option_a, option_b, option_c, option_d, option_e, correct_option, pdf_page_ref, owner_id) VALUES ('VUNESP - ASJ (TJ SP)/TJ SP/2025
Língua Portuguesa (Português) - Tipologia e Gênero Textual

1) 

Leia o texto a seguir para responder à questão abaixo.

Uma nova era para a China

A China encerrou 2024 com dois feitos notáveis. O primeiro: o Produto Interno Bruto (PIB) do país cresceu no ano passado os 5% que o governo tinha como meta,
ligeiramente abaixo dos 5,2% de 2023. Trata-se de crescimento invejável para a maioria dos países, mas muito aquém daquele que o gigante asiático já produziu em
um passado não tão distante.

Reproduzir tal façanha nos próximos anos, contudo, parece cada vez mais improvável. Oficialmente, o governo chinês ainda sonha com crescimento de 5% no futuro
próximo, mas tal desempenho exigirá bem mais que os estímulos dados por Pequim e que garantiram o cumprimento da meta de crescimento em 2024.

Desafios como a queda dos preços das casas no obscuro mercado imobiliário chinês, desemprego acima de dois dígitos entre os mais jovens e consumo interno fraco
são problemas estruturais com os quais Pequim vem tentando lidar com o gradualismo que lhe é característico.

Outro ponto de atenção é o encolhimento populacional, mesmo para um país com mais de 1 bilhão de habitantes.
A China registrou declínio de população nos últimos três anos, indicativo de que os chineses, que contam com aparato muito reduzido de proteção social, têm optado
por não ter filhos, ou seja, cai o número de trabalhadores e consumidores tão necessários a uma economia que precisará fortalecer cada vez mais a demanda interna.

Isto porque o segundo feito notável conquistado pela China no ano passado, o superávit comercial de quase US$ 1 trilhão (mais de R$ 6 trilhões), não apenas não deve
se repetir, como certamente será utilizado pelo presidente dos Estados Unidos, Donald Trump, como mais um argumento para limitar as importações norte-americanas
de produtos chineses.

A China sabe que precisa calibrar sua política econômica porque o modelo atual, em grande parte bem-sucedido até aqui, pode enfraquecer ainda mais seu mercado
doméstico. Os Estados Unidos sabem que precisam diminuir seu déficit comercial gigantesco, pois ele elimina empregos bem remunerados para os norte-americanos,
entre outros problemas.

Uma nova era se anuncia para a China. Ao Brasil, que sabiamente resistiu a aderir à Nova Rota da Seda e vem aumentando tarifas de importação sobre veículos
elétricos chineses, será necessária ainda mais racionalidade. Do contrário, o País sairá chamuscado na guerra entre as duas potências econômicas globais.

(O Estado de S.Paulo, Opinião, “Uma nova era para a China”, 19.01.2025. Disponível em: https://www.estadao.com.br/opiniao/ uma-nova-era-para-a-china/. Adaptado)

A tipologia textual predominante no texto é a', 'expositiva, pois tem como objetivo a explicação dos impactos mundiais das medidas protetivas comerciais do Brasil.', 'injuntiva, pois tem como objetivo a interlocução direta com o leitor para que entenda o contexto da economia chinesa.', 'narrativa, pois tem como objetivo o relato pormenorizado das relações comerciais entre a China e os Estados Unidos.', 'descritiva, pois tem como objetivo a apresentação das características da conjuntura atual chinesa e os desafios que o país enfrenta.', 'argumentativa, pois tem como objetivo a análise da conjuntura econômica atual e sua relação com os Estados Unidos e o Brasil.', 'A', 1, NULL);
INSERT IGNORE INTO questions (statement, option_a, option_b, option_c, option_d, option_e, correct_option, pdf_page_ref, owner_id) VALUES ('Instituto Verbena - GCM (C Ocidental)/Pref C Ocidental/2023

Língua Portuguesa (Português) - Tipologia e Gênero Textual

2) 

Leia o Texto 1 para responder à questão seguinte.

Texto 1

<div style=''text-align:center''><img src=''assets/uploads/images/visual_p1_1.png'' class=''question-image'' style=''max-width:100%; margin: 10px 0; border: 1px solid #eee;''></div>Disponível em: <https://ferrazdevasconcelos.sp.gov.br/web/campanhacriativa- da-secretaria-de-comunicacao-de-ferraz-impulsiona-vacinacaocontra- covid-19/>. Acesso em: 03 set. 2023.

A construção de sentido da campanha publicitária apresenta uma perspectiva', 'informativa e humorística.', 'descritiva e irônica.', 'imperativa e analítica.', 'científica e crítica.', '', 'A', 1, NULL);
INSERT IGNORE INTO questions (statement, option_a, option_b, option_c, option_d, option_e, correct_option, pdf_page_ref, owner_id) VALUES ('VUNESP - DG (CM Potim)/CM Potim/2021
Língua Portuguesa (Português) - Tipologia e Gênero Textual

3) 

     Quem se espanta com o espetáculo de horror diversificado que o mundo de hoje oferece faria bem se tivesse o dicionário como livro de leitura diurna e noturna.
Pois ali está, na letra M, a chave do temperamento homicida, que convive no homem com suas tendências angélicas, e convive em perfeita harmonia de namorados.

    O consulente verá que matar é verbo copiosamente conjugado por ele próprio, não importa que cultive a mansuetude, a filantropia, o sentimentalismo; que
redija projetos de paz universal, à maneira de Kant, e considere abominações o assassínio e o genocídio. Vive matando.

    A ideia de matar é de tal modo inerente ao homem que, à falta de atentados sanguinolentos a cometer, ele mata calmamente o tempo. Sua linguagem o trai. Por
que não diz, nas horas de ócio e recreação ingênua, que está vivendo o tempo? Prefere matá-lo.

    Todos os dias, mais de uma vez, matamos a fome, em vez de satisfazê-la. O estudante que falta à classe confessa que matou a aula, o que implica matança do
professor, da matéria e, consequentemente, de parte do seu acervo individual de conhecimento, morta antes de chegar a destino. No jogo mais intelectual que se
conhece, pretende-se não apenas vencer o competidor, mas liquidá-lo pela aplicação de xeque-mate. Não admira que, nas discussões, o argumento mais poderoso se
torne arma de fogo de grande eficácia letal: mata na cabeça.

    Beber um gole no botequim, ato de aparência gratuita, confortador e pacificante, envolve sinistra conotação. É o mata-bicho, indiscriminado. Matar charadas
constitui motivo de orgulho intelectual para o matador.

    Se a linguagem espelha o homem, e se o homem adorna a linguagem com tais subpensamentos de matar, não admira que os atos de banditismo, a explosão
intencional de aviões, o fuzilamento de reféns, o bombardeio aéreo de alvos residenciais, os pogroms, o napalm, as bombas A e H, a variada tragédia dos dias
modernos se revele como afirmação cotidiana do lado perverso do ser humano.

    Admira é que existam a pesquisa de antibióticos, Cruz Vermelha Internacional, Mozart, o amor.

(Carlos Drummond de Andrade, O verbo matar. Poesia e Prosa. Adaptado.)

Em relação ao conjunto do texto, a afirmação contida no último parágrafo representa', 'um contraponto, com a apresentação de elementos em que se destacam aspectos incompatíveis com a ideia de matar.', 'um contrassenso, com a apresentação de elementos de diferentes naturezas, sem um aspecto comum que os aproxime.', 'uma conclusão lógica, indissociável do contexto anterior, por reforçar os pressupostos nele afirmados.', 'um questionamento pertinente, por lançar ideias novas acerca das potencialidades da linguagem.', 'uma abordagem filosófica do tema, com a explicitação de um juízo moral acerca da ideia de morte.', 'A', 1, NULL);
INSERT IGNORE INTO questions (statement, option_a, option_b, option_c, option_d, option_e, correct_option, pdf_page_ref, owner_id) VALUES ('VUNESP - An L (CM Mogi Mirim)/CM Mogi-Mirim/2020
Língua Portuguesa (Português) - Tipologia e Gênero Textual

4) 

Leia o texto de Lygia Fagundes Telles para responder a questão.

No princípio era o caderno

Quando mocinhas, elas podiam escrever seus pensamentos e estados d’alma (em prosa e verso) nos diários de capa acetinada com vagas pinturas representando flores
ou pombinhos brancos levando um coração no bico. Nos diários mais simples, cromos coloridos de cestinhos floridos ou crianças abraçadas a um cachorro. Depois de
casadas, não tinha mais sentido pensar sequer em guardar segredos, que segredo de mulher casada só podia ser bandalheira. Restava o recurso do cadernão do dia a
dia, onde, de mistura com os gastos da casa cuidadosamente anotados e somados no fim do mês, elas ousavam escrever alguma lembrança ou uma confissão que se
juntava na linha adiante com o preço do pó de café e da cebola.

Minha mãe guardava um desses cadernos que pertencera à minha avó Belmira. Me lembro da capa dura, recoberta com um tecido de algodão preto. A letrinha
vacilante, bem desenhada, era menina quando via minha mãe recorrer a esse caderno para conferir uma receita de doce ou a receita de um gargarejo. “Como mamãe
escrevia bem! – Observou ela mais de uma vez. – Que pensamentos e que poesias, como era inspirada!”.

Vejo nas tímidas inspirações desse cadernão (que se perdeu num incêndio) um marco das primeiras arremetidas da mulher brasileira na chamada carreira de letras –
um ofício de homem.

(A disciplina do amor. Rocco, 1998.)

Pelas ideias apresentadas, é correto afirmar que o texto é', 'poético, por conta da linguagem prolixa empregada pela narradora e do caráter estritamente ficcional dos eventos relatados.', 'confessional, pois a narradora recorda e analisa situações constrangedoras vivenciadas durante sua infância.', 'de depoimento, já que o relato e a consequente reflexão sobre os eventos ocorridos estão associados a experiências da própria narradora.', 'de crítica, uma vez que a narradora lamenta o número restrito de novas escritoras no contexto literário atual.', 'de cunho histórico, visto que a narradora determina, com base acadêmica, o período em que nasceu a literatura feminina em nosso país.', 'A', 1, NULL);
INSERT IGNORE INTO questions (statement, option_a, option_b, option_c, option_d, option_e, correct_option, pdf_page_ref, owner_id) VALUES ('VUNESP - Adm Jud (TJ SP)/TJ SP/2019

Língua Portuguesa (Português) - Tipologia e Gênero Textual

5) 

Leia o texto para responder à questão.

Procuram-se especialistas em evitar fraudes

A recente onda de escândalos de corrupção levou as empresas brasileiras a investir em uma área ainda pouco conhecida no mercado: o compliance.

O profissional que atua nesse setor é responsável por receber denúncias, combater fraudes, realizar investigações internas e garantir que a companhia cumpra leis,
acordos e regulamentos da sua área de atuação. Ele tem o papel importante de auxiliar a empresa a se proteger de eventuais problemas de corrupção.

“Nos últimos anos, a área de compliance assumiu protagonismo nas empresas. É uma profissão com salários altos já que as pessoas com experiência ainda são escassas
no mercado”, diz o advogado Thiago Jabor Pinheiro, 35.

“Como não existem cursos de graduação específicos de compliance, o estudante que se interesse pela área pode direcionar seu curso para questões de auditoria,
prevenção de fraude, direito administrativo e governança corporativa”, diz Pinheiro.

Apesar de sobrarem vagas nesse mercado, conseguir um emprego não é fácil. “É fundamental que a pessoa seja atenta aos detalhes, entenda como funciona uma
organização e tenha fluência em inglês porque as melhores práticas vêm de fora do país, sobretudo dos EUA e da Inglaterra”, diz o advogado.

Para Caroline Cadorin, diretora de uma consultoria, os candidatos precisam ter jogo de cintura para lidar com as mais diversas situações. “Estamos falando de
profissionais com forte conduta ética, honestidade e que buscam a promoção da transparência. Hoje as empresas estão cientes de seus papéis ativos no combate à
corrupção, especialmente aquelas envolvidas em projetos de órgãos públicos. As companhias que mantêm departamentos de compliance são vistas como mais
transparentes”, diz Cadorin.

 
(Larissa Teixeira. Folha de S.Paulo, 28.09.2017. Adaptado)

 
Analisando-se a organização do quinto parágrafo do texto, conclui-se que ele é:', 'descritivo-narrativo.', 'descritivo-argumentativo.', 'estritamente argumentativo.', 'argumentativo-narrativo.', 'estritamente descritivo.', 'A', 1, NULL);
INSERT IGNORE INTO questions (statement, option_a, option_b, option_c, option_d, option_e, correct_option, pdf_page_ref, owner_id) VALUES ('VUNESP - Dir DF (CM Jales)/CM Jales/2018
Língua Portuguesa (Português) - Tipologia e Gênero Textual

6) 

Alguém ainda se lembra do telefone de todas as tias, dos tios, dos primos, dos avós ou dos vizinhos? Na minha casa era assim. Minha mãe, por exemplo, sabia o
telefone de todo mundo. Parecia até que o Catálogo Telefônico era o seu livro de cabeceira.

— Mãe, qual é o telefone de tia Lili?
— 2-4036.

Sim, os números eram mais curtos, mas, mesmo assim, eu ficava impressionado ao ver como ela sabia de cor, como ela tinha na cabeça o telefone de todos os
parentes e também do açougue, do armazém, da farmácia, do Colégio Marista e do Colégio Sion.

Hoje, todos nós ficamos preguiçosos. Quando roubaram o meu smartphone, só fui contar o ocorrido em casa, porque não sabia o telefone de ninguém, da mulher, dos
filhos, nem mesmo o fixo que fica no meu escritório.

Mas lembrar número de telefone não é nada. Ficamos preguiçosos pra tudo. Pra subir escada, pra rodar a manivela do vidro do carro, pra levantar e mudar o canal da
TV.

Ficamos preguiçosos pra ir de um lugar pra outro sem usar o Waze*. Já reparou que não se vê mais ninguém abrindo o vidro do carro e perguntando pro pedestre:

— Por favor, onde fica a rua Apinagés?

Para você ir do início da Avenida Paulista até o final dela, é só seguir reto, mas você coloca no Waze. E o pior é que às vezes ao invés de ele dizer “siga em frente toda
vida”, como um bom mineiro, ele informa:

— A 100 metros, vire à esquerda.

Foi o que aconteceu comigo dentro de um taxi. O motorista argumentou que era pra evitar o trânsito. Passamos por Pinheiros, pela Vila Madalena, por Perdizes pra ir
do início ao fim da Avenida Paulista.

(Alberto Villas. “Você chegou ao seu destino!”. www.cartacapital.com.br. 02.03.2018. Adaptado)

* Waze: aplicativo de navegação por GPS que informa as condições do trânsito.

No texto, o autor apresenta', 'uma reflexão acerca do modo como a tecnologia gera exclusão social.', 'uma crítica aos hábitos que passam de uma geração a outra.', 'uma sátira sobre a dependência excessiva da tecnologia na atualidade.', 'um desabafo bem-humorado sobre sua recusa em usar aparatos eletrônicos.', 'um arrazoado em favor da proibição do uso de aplicativos no transporte.', 'A', 1, NULL);
INSERT IGNORE INTO questions (statement, option_a, option_b, option_c, option_d, option_e, correct_option, pdf_page_ref, owner_id) VALUES ('VUNESP - Ag Tel Pol (PC SP)/PC SP/2018
Língua Portuguesa (Português) - Tipologia e Gênero Textual

7) 

Frei Caneca e a Virgem Maria

No dia 13 de janeiro de 1825, um condenado caminhava com passos firmes na direção da forca, no centro do Recife. Era o frei Joaquim do Amor Divino Caneca, o
lendário Frei Caneca, lutador incansável pela independência do Brasil. Ele tinha participado da revolta da Confederação do Equador, sufocada pelo governo de
Pernambuco. Vestia o hábito da Irmandade da Madre de Deus. Sob o olhar curioso da multidão, foi submetido ao degradante ritual da desautoração*, perdendo os
direitos eclesiásticos, para que pudesse enfrentar o suplício da forca.

Impassível e altivo, deixou que os monges despissem suas vestes sagradas. Permaneceu firme quando recebeu na tonsura** o golpe simbólico da excomunhão. O
carrasco já se preparava para o gesto fatal, quando recuou, com o rosto pálido, dizendo que a Virgem Maria estava junto ao condenado. Veio então o ajudante do
carrasco, que também se recusou a executar Frei Caneca, diante da visão da Virgem Maria. Aí foram buscar dois escravos. E esses, mesmo duramente açoitados,
negaram-se a participar da execução. O juiz mandou trazer dois presos da cadeia pública e lhes ofereceu a liberdade em troca da execução de Frei Caneca. E eles
igualmente se negaram, alegando a visão da Virgem Maria.

Mas era preciso matar Frei Caneca de qualquer jeito, como exemplo para desencorajar futuros conspiradores. O juiz então ordenou que ele fosse fuzilado. Percebendo
que os soldados tremiam com as armas na mão, Frei Caneca procurou exortá-los:

– Vamos, meus amigos. Não me façam sofrer muito. Virgem Maria há de compreender os vossos temores. Tenham fé, ela já os perdoou.

E os tiros provocaram um arrepio na multidão silenciosa.

(Eloy Terra. 500 anos: Crônicas pitorescas da história do Brasil. Adaptado)

*Desautoração: privação da dignidade do cargo, como medida punitiva.

**Tonsura: corte redondo dos cabelos no topo da cabeça dos clérigos.

Considerando-se as características do texto, é correto afirmar que se trata do tipo', 'dissertativo, com discussão de ideias.', 'dissertativo, com pontos de vista de personagens.', 'narrativo, com apresentação de uma tese.', 'descritivo, com caracterização de ambiente.', 'narrativo, com exposição de fatos.', 'A', 1, NULL);
INSERT IGNORE INTO questions (statement, option_a, option_b, option_c, option_d, option_e, correct_option, pdf_page_ref, owner_id) VALUES ('VUNESP - Jorn (CM Valinhos)/CM Valinhos/2017
Língua Portuguesa (Português) - Tipologia e Gênero Textual

8) 

Fascínio

De todos aqueles ratos de cinemateca que formaram a Nova Onda do cinema francês no final dos anos 60, só Truffaut ficou. Eu sei que os outros continuam aí, fazendo
boas coisas, mas só de Truffaut pode-se dizer que se estabeleceu no ramo do cinema. A noite americana mostra o porquê. Truffaut nunca pretendeu do cinema nada
além do cinema. O mais admirável em A noite americana é a sua contenção, a sua extrema economia de propósitos. Outro diretor teria aproveitado a oportunidade —
um filme sobre a feitura de um filme — para armar um jogo intelectual qualquer, um truque de espelhos, a fantasia e a realidade, a arte e a vida, e olhem só como eu
sou engenhoso. Truffaut, não. Faz um filme convencional sobre Truffaut fazendo um filme convencional. Mas Truffaut faz grandes filmes convencionais.

Não é que ele seja superficial. Fellini também é um superficial e substitui as ideias pelo barroquismo de imagem. Está certo, a imagem inteligente é uma das formas
que o cinema tem de ser profundo. Truffaut não se interessa em ser profundo. A primeira mágica do cinema, o fato do cinema em si, já basta como fascínio. Nada de
muito extraordinário acontece em A noite americana, e a grande homenagem de Truffaut ao cinema é transformar o fato corriqueiro de um filme sendo feito num
espetáculo extraordinário. Truffaut, como todos da sua geração, começou no cinema pelo deslumbramento. A diferença entre ele e o resto é que ele continua
deslumbrado. Durante as quase duas horas de A Noite americana, o cinema reina e nos emociona.

Profundamente. E Truffaut está tão comovido quanto a gente.

(Luis Fernando Verissimo. Banquete com
os deuses: cinema, literatura, música e outras artes. Rio de Janeiro, Objetiva, 2011. Adaptado)

No trecho selecionado do texto, uma aparente contradição na argumentação do autor evidencia-se no emprego da palavra destacada em:', 'O mais admirável em A noite americana é a sua contenção, a sua extrema economia de propósitos. (1º parágrafo)', 'Truffaut, não. Faz um filme convencional sobre Truffaut fazendo um filme convencional. (1º parágrafo)', 'Não é que ele seja superficial. Fellini também é um superficial e substitui as ideias pelo barroquismo de imagem. (2º parágrafo)', 'Truffaut não se interessa em ser profundo. A primeira mágica do cinema, o fato do cinema em si, já basta como fascínio. (2º parágrafo)', 'Truffaut, como todos da sua geração, começou no cinema pelo deslumbramento. A diferença entre ele e o resto é que ele continua deslumbrado. (2º
parágrafo)', 'A', 1, NULL);
INSERT IGNORE INTO questions (statement, option_a, option_b, option_c, option_d, option_e, correct_option, pdf_page_ref, owner_id) VALUES ('VUNESP - Aux Lg (CM Itanhaém)/CM Itanhaém/2017

Língua Portuguesa (Português) - Tipologia e Gênero Textual

9) 

Leia o texto, para responder à questão.

<div style=''text-align:center''><img src=''assets/uploads/images/visual_p4_2.png'' class=''question-image'' style=''max-width:100%; margin: 10px 0; border: 1px solid #eee;''></div>(Ciça, Pagando o pato)

É correto concluir que o humor da tira decorre', 'do emprego de frases na forma negativa.', 'da impertinência da pergunta do pato.', 'da manifestação de inconformismo da formiga.', 'da exploração do duplo sentido de palavra.', 'da falta de sentido das palavras empregadas pelas personagens.', 'A', 1, NULL);
INSERT IGNORE INTO questions (statement, option_a, option_b, option_c, option_d, option_e, correct_option, pdf_page_ref, owner_id) VALUES ('Instituto Verbena - GM (Sen Can)/Pref Sen Can/2014
Língua Portuguesa (Português) - Tipologia e Gênero Textual

10) 

Leia o texto a seguir para responder à questão.

A Guarda Municipal e a Segurança Pública

Um processo histórico não acontece da noite para o dia, não é uma simples equação em que se chega a um resultado numérico. É um processo que depende de
inúmeros eixos notadamente estudados pela História: humanos, políticos, sociais, dentre tantos. Podemos considerar que estamos vivendo um processo de evolução na
segurança pública no Brasil, já que velhas práticas coexistem com novas propostas: a adoção do policiamento comunitário, proativo, a garantia dos direitos individuais
e a liberdade de expressão, esta última ainda que por vezes cerceada.

O entendimento sobre segurança pública, ainda que ferrenhamente não aceito por alguns, também está evoluindo, deixando para trás o simplismo que atribui
segurança pública à polícia. Nesse contexto, a participação do município foi colocada em evidência, basicamente na elaboração de estratégias preventivas, seja no
seu espaço físico, seja na orientação à população ou ainda na utilização de mecanismos tecnológicos diversos. Não foi ao acaso ou por impedimento legal que coube
ao município agir preventivamente. Está mais do que provado que a simples repressão não reduz a criminalidade, tampouco controla a origem da violência, só mantém
os órgãos de segurança a situações de ação e reação.

Assim, quando se estuda a imprescindível participação do município na segurança pública, temos por pilar principal de sustentação de qualquer ação preventiva a
Guarda Municipal. Por muito tempo, o mesmo simplismo que reduziu a segurança pública a problemas da polícia, também reduziu as Guardas Municipais (utilizo o
termo no plural, pois esses problemas são comuns a todas as corporações municipais) a cuidar do patrimônio público. As Guardas Municipais [...] podem e devem ter
uma ação muito mais ampla do que cuidar do patrimônio público.

Para realizar esta proteção, utiliza-se de duas formas distintas: a Guarda Municipal em um posto fixo e em viaturas realizando o patrulhamento ostensivo de várias
instalações municipais. Essa segunda forma é dinâmica, têm grande mobilidade de ação, pode ser alterada conforme a necessidade operacional e auxilia a população
de inúmeras outras formas. [...] As Guardas Municipais colaboram e se fazem necessárias nas cidades preocupadas em estabelecer uma política municipal de
segurança, realizando com profissionalismo ações de segurança pública.

Antes relegadas a segundo plano, as Guardas Municipais têm hoje uma participação plena no cenário conturbado da segurança pública e não se pode tratar do assunto
de forma irresponsável, com uma seleção e uma formação pífia, pois segurança pública diz respeito a duas condições fundamentais: a vida e a liberdade.

BERNI, Dênis. Disponível em: <http://votoconscientejundiai.com.br/cidadania/guarda-municipal-e-seguranca-publica/> Acesso em: 14 jan. 2014. (Adaptado).

O texto de Dênis Berni pode ser considerado um artigo de opinião porque', 'mobiliza sequências expositivas para tornar conceitos científicos acessíveis.', 'seleciona argumentos em favor da defesa de um ponto de vista.', 'orienta os guardas municipais no exercício de sua função.', 'propõe alterações no plano diretor dos municípios.', '', 'A', 1, NULL);
INSERT IGNORE INTO questions (statement, option_a, option_b, option_c, option_d, option_e, correct_option, pdf_page_ref, owner_id) VALUES ('VUNESP - Of Com (CM Sorocaba)/CM Sorocaba/2014
Língua Portuguesa (Português) - Tipologia e Gênero Textual

11) 

Considere a ilustração a seguir.

<div style=''text-align:center''><img src=''assets/uploads/images/visual_p5_3.png'' class=''question-image'' style=''max-width:100%; margin: 10px 0; border: 1px solid #eee;''></div>(Bom dia Sorocaba, 19.09.2011)

A ilustração é', 'um cartum.', 'uma tira.', 'uma caricatura.', 'uma pantomina.', 'uma charge.', 'A', 1, NULL);
INSERT IGNORE INTO questions (statement, option_a, option_b, option_c, option_d, option_e, correct_option, pdf_page_ref, owner_id) VALUES ('VUNESP - Ag Jorn (CMBP)/CM BP/2013

Língua Portuguesa (Português) - Tipologia e Gênero Textual

12) 

Mas o que é isso?

Outro dia apresentei um dos espetáculos do meu grupo de dança para pessoas com deficiência em um teatro aqui de Brasília e, logo após a apresentação, fizemos um
bate-papo com o pessoal que foi assistir.

Entendo que essa ideia de um grupo de dança que mistura pessoas com e sem deficiência no palco ainda é um tanto recente aqui em Brasília e poucas pessoas viram
espetáculos assim. Por isso, acho curioso esse bate-papo final. Surgem tantas questões e comentários interessantes que daria para escrever um livro só com eles.

Um dos comentários mais comuns é em relação à superação. As pessoas ficam muito emocionadas e dizem que é muito lindo ver a superação das pessoas com
deficiência dançando. Com o passar do tempo e conforme fomos trabalhando, começamos a nos questionar: por que quando eu danço, eu apenas trabalhei e estudei
para aprender aquilo e, por isso, estou dançando, mas a pessoa com deficiência superou limites? Ela não pode ter apenas trabalhado muito para adquirir aquele
conhecimento, assim como todos nós?

As pessoas também costumam elogiar muito o trabalho dos professores, dizendo que o que a gente faz é maravilhoso. Já chegaram até a dizer que é quase milagroso!
Ah, se essas pessoas imaginassem o quanto a gente aprende com nossos alunos que têm deficiência, elas elogiariam o trabalho deles, o esforço deles, pois para a
gente não é esforço nenhum estar com eles!

Bom, mas nessa última apresentação surgiram umas perguntas diferentes. Primeiro perguntaram o que é dança para a gente. Bom, o que é dança? Dança é
movimento. Como todos nós, que estamos vivos, nos mexemos – pois piscamos, respiramos, nossos corações batem –, todos nós podemos dançar! Dança nada mais é do
que fazer poesia com o corpo. E então surgiu a outra pergunta que rendeu um belo debate para o resto da noite: E então, o que é poesia?

O que é poesia? Dentre tantas respostas e discussões, acho que poesia pode ser o que você quiser que seja! O nosso dia, se quisermos, pode ser repleto de poesia!
Alguns vão para o trabalho focados apenas no trânsito e em chegar logo, outros vão observando a luz do sol refletida na poça de água que foi formada pela chuva,
sorriem e se sentem presenteados quando aquela música que adoram começa a tocar na rádio! Atos corriqueiros, que fazemos sem prestar atenção, um dia, podem
nos proporcionar uma experiência nova. Essa experiência pode ser poesia, não pode?

(Clara Braga, www.cronicadodia.com.br, 26.06.2013. Adaptado)

O significado de poesia apresentado no texto é, na opinião da autora,', 'subjetivo.', 'consensual.', 'irretocável.', 'inquestionável.', 'categórico.', 'A', 1, NULL);
INSERT IGNORE INTO questions (statement, option_a, option_b, option_c, option_d, option_e, correct_option, pdf_page_ref, owner_id) VALUES ('Instituto Verbena - GM (Aparecida GO)/Pref Aparecida GO/2012
Língua Portuguesa (Português) - Tipologia e Gênero Textual

13) 

Texto 2

Autos n.º                 109.08.000577 -0
Ação                        Ação Penal/Sumário
Tipo
Réu
Mandado n.º            109.2009/000302-7
Oficial de Justiça      José Pereira Sobrinho ( 1901 ) / Zona: Zona única

MANDADO DE INTIMAÇÃO

(Audiência)

O(A) Doutor(a) Marcos José Sampaio de Freitas Júnior, Juiz de Direito Substituto desta Comarca de Acari, Estado de Rio Grande do Norte, na forma da lei etc.

MANDA a qualquer dos Oficiais de Justiça deste Juízo a quem o presente mandado for  entregue, estando devidamente assinado e quem no cumprimento do seu cargo,
INTIME a(s) pessoa(s) abaixo relacionadas, informando-as de que, diante da premente necessidade de impulsionamento e julgamento dos feitos inseridos na META 2 do
CNJ, e tendo em conta o acúmulo de atribuições deste Magistrado nesta Comarca e na Vara Cível da Comarca de Currais Novos/RN, bem como na 22ª Zona Eleitoral, a
audiência designada nos autos do processo acima mencionado foi redesignada para o dia 25 de fevereiro de 2012, ás 08:30h, devendo comparecerem ao ato
redesignado no dia e horário referidos.

 
Disponível em: <www.robsonpiresxerife.com/blog/>. 

Acesso em: 19 mar. 2012. [adaptado]

Os gêneros do discurso jurídico têm uma estrutura mais ou menos fixa e devem obedecer a determinados critérios formais para que surtam efeitos legais. O trecho do
texto  que remete ao ato do juiz sem o qual a intimação não surte efeito para os intimados é:', '“Manda qualquer dos oficiais de justiça”.', '“na forma da lei”.', '“estando devidamente assinado”.', '“nos autos do processo acima mencionado”.', '', 'A', 1, NULL);
INSERT IGNORE INTO questions (statement, option_a, option_b, option_c, option_d, option_e, correct_option, pdf_page_ref, owner_id) VALUES ('Instituto Verbena - GM (Aparecida GO)/Pref Aparecida GO/2012
Língua Portuguesa (Português) - Tipologia e Gênero Textual

14) 

Texto 3

<div style=''text-align:center''><img src=''assets/uploads/images/visual_p6_4.png'' class=''question-image'' style=''max-width:100%; margin: 10px 0; border: 1px solid #eee;''></div> 
Disponível em:<intimaçãomodaintima.blogspot.com>. 

Acesso em: 19 mar. 2012. [adaptado]

Toda “intimação” tem uma conotação imperativa e é expressa formalmente por diferentes tipos de enunciados. No texto, por exemplo, esse sentido é expresso por
uma sequência', 'descritiva: referência direta aos efeitos e ao tipo de produto anunciado.', 'narrativa: sequenciação espacial e temporal das vantagens do produto.', 'dialogal: marcação das vozes envolvidas no processo de compra e venda.', 'argumentativa: justificativa explícita da escolha do produto pelo consumidor.', '', 'A', 1, NULL);
INSERT IGNORE INTO questions (statement, option_a, option_b, option_c, option_d, option_e, correct_option, pdf_page_ref, owner_id) VALUES ('Instituto Verbena - GM (Aparecida GO)/Pref Aparecida GO/2012
Língua Portuguesa (Português) - Tipologia e Gênero Textual

15) 

Texto 1

Intimação

Abre em nome da lei.
Em nome de que lei?
Acaso lei sem nome?
Em nome de que nome
cujo agora me some
se em sonho o soletrei?
Abre em nome do rei.
Em nome de que rei
é a porta arrombada
para entrar o aguazil
que na destra um papel
sinistramente branco
traz, e ao ombro o fuzil?
Abre em nome de til.
Abre em nome de abrir,
em nome de poderes
cujo vago pseudônimo
não é de conferir:
cifra oblíqua na bula
ou dobra na cogula
de inexistente frei.
Abre em nome da lei.
Abre sem nome e lei.
Abre mesmo sem rei.
Abre sozinho ou grei.
Não, não abras; à força
de intimar-te repara:

eu já te desventrei.

 
ANDRADE, Carlos Drummond de. Disponível em:
<www..terra.com.br/poesia/>. Acesso em: 20 mar. 2012

 
Texto 2

Autos n.º                 109.08.000577 -0
Ação                        Ação Penal/Sumário
Tipo
Réu
Mandado n.º            109.2009/000302-7
Oficial de Justiça      José Pereira Sobrinho ( 1901 ) / Zona: Zona única

MANDADO DE INTIMAÇÃO

(Audiência)

O(A) Doutor(a) Marcos José Sampaio de Freitas Júnior, Juiz de Direito Substituto desta Comarca de Acari, Estado de Rio Grande do Norte, na forma da lei etc.

MANDA a qualquer dos Oficiais de Justiça deste Juízo a quem o presente mandado for  entregue, estando devidamente assinado e quem no cumprimento do seu cargo,
INTIME a(s) pessoa(s) abaixo relacionadas, informando-as de que, diante da premente necessidade de impulsionamento e julgamento dos feitos inseridos na META 2 do
CNJ, e tendo em conta o acúmulo de atribuições deste Magistrado nesta Comarca e na Vara Cível da Comarca de Currais Novos/RN, bem como na 22ª Zona Eleitoral, a
audiência designada nos autos do processo acima mencionado foi redesignada para o dia 25 de fevereiro de 2012, ás 08:30h, devendo comparecerem ao ato
redesignado no dia e horário referidos.

 
Disponível em: <www.robsonpiresxerife.com/blog/>. 

Acesso em: 19 mar. 2012. [adaptado]

 
Texto 3

<div style=''text-align:center''><img src=''assets/uploads/images/visual_p7_5.png'' class=''question-image'' style=''max-width:100%; margin: 10px 0; border: 1px solid #eee;''></div> 
Disponível em:<intimaçãomodaintima.blogspot.com>. 

Acesso em: 19 mar. 2012. [adaptado]
Os textos 1, 2 e 3 distinguem-se pelo tipo de interlocutor a que a intimação é dirigida. A especificação desse interlocutor é determinada', 'pelo uso dos verbos no imperativo.', 'pela formalidade da linguagem utilizada.', 'pelo tema explorado no texto.', 'pela sequência textual predominante.', '', 'A', 1, NULL);
INSERT IGNORE INTO questions (statement, option_a, option_b, option_c, option_d, option_e, correct_option, pdf_page_ref, owner_id) VALUES ('VUNESP - AJ (TJ MT)/TJ MT/Letras/2008
Língua Portuguesa (Português) - Tipologia e Gênero Textual

16) 

Desde que nasce a ciência – com a experimentação, em inícios da modernidade –, ela mantém uma relação difícil com a ética. No século 16, os bons costumes
vêem com horror a prática da anatomia, que, no entanto, será a condição básica para se desenvolver a medicina (e também a pintura: Da Vinci não seria o mesmo se
não tivesse examinado cadáveres, para desenhar o corpo humano). Nos princípios do século 20, Freud causa escândalo quando afirma a sexualidade infantil. Esses
exemplos bastam: a medicina do corpo e da psique surgem causando um horror moral. Daí, a pergunta: quando criticamos um avanço científico em nome da ética, não
corremos o risco de ser tão preconceituosos, em face do novo, quantos foram os que condenaram Da Vinci pela anatomia, Freud pela sexualidade infantil?

(Renato Janine Ribeiro. Pesquisa Fapesp, n.o 73 – Suplemento Especial. Adaptado)

No texto, destaca-se como recurso básico a argumentação por', 'incompatibilidade.', 'exemplo.', 'definição.', 'regra de justiça.', 'retorsão.', 'A', 1, NULL);
INSERT IGNORE INTO questions (statement, option_a, option_b, option_c, option_d, option_e, correct_option, pdf_page_ref, owner_id) VALUES ('VUNESP - AJ (TJ MT)/TJ MT/Letras/2008
Língua Portuguesa (Português) - Tipologia e Gênero Textual

17) 

O físico José Goldemberg falou ao jornal “Valor Econômico” sobre quatro mitos que rondam combustíveis renováveis, todos negativos, e que acabam por
contaminar o álcool de cana. Ei-los: biocombustíveis causam desmatamento; estão provocando fome no mundo; seu efeito sobre a emissão de gases do efeito estufa é
nulo; seriam viáveis apenas em nichos, como o brasileiro.

A primeira afirmação, segundo Goldemberg, não é válida nem para os Estados Unidos nem para o Brasil, os dois maiores produtores. Nos Estados Unidos, a matéria-
prima do álcool é milho, cujo cultivo avança sobre áreas de soja, e não sobre terras virgens (artigo raro por lá).

Aqui, as lavouras de cana ocupam superfície comparável à do Rio Grande do Norte, mas isso corresponde a meros 2% dos 2,9 milhões de km2 utilizados pelo setor

agropecuário. E o aumento da área canavieira, inegável, costuma ocorrer pela conversão de pastagens. Para o físico, a cana não contribui nem mesmo de modo
indireto para desmatar a Amazônia, pois o espaço ocupado por pastos está até diminuindo – é a produtividade da pecuária que aumenta.

O segundo equívoco Goldemberg descarta com outro dado objetivo: a agricultura de todos os países juntos se espalha por 12 milhões de km2 do planeta, mas só 100
mil km2 são destinados a biocombustíveis nos EUA e no Brasil. Ou seja, os “críticos perderam completamente o senso de proporção”.

O terceiro mito, do suposto balanço energético desfavorável dos biocombustíveis, é rebatido pelo entrevistado com uma condenação ao álcool de milho. Este produz
apenas 1,5 unidade de energia renovável para cada unidade de energia fóssil (petróleo empregado para produzir fertilizantes ou diesel para máquinas, por exemplo).
O álcool de cana, por seu turno, rende oito. Vale dizer, o etanol brasileiro é cinco vezes mais eficiente para substituir combustíveis que agravam o aquecimento
global.

Por fim, Goldemberg derruba a quarta mistificação, assinalando que apenas 25% da cana mundial está plantada no Brasil. Há canaviais em vários outros países
tropicais, como os da América Central e da África, para citar duas regiões com grande potencial de expansão.

(Folha de S.Paulo, 28.04.2008. Adaptado)

Pode-se classificar esse texto como', 'objetivo.', 'neutro.', 'pessimista.', 'faccioso.', 'emocional.', 'A', 1, NULL);
INSERT IGNORE INTO questions (statement, option_a, option_b, option_c, option_d, option_e, correct_option, pdf_page_ref, owner_id) VALUES ('VUNESP - AJ (TJ MT)/TJ MT/Letras/2008
Língua Portuguesa (Português) - Tipologia e Gênero Textual

18) 

O físico José Goldemberg falou ao jornal “Valor Econômico” sobre quatro mitos que rondam combustíveis renováveis, todos negativos, e que acabam por
contaminar o álcool de cana. Ei-los: biocombustíveis causam desmatamento; estão provocando fome no mundo; seu efeito sobre a emissão de gases do efeito estufa é
nulo; seriam viáveis apenas em nichos, como o brasileiro.

A primeira afirmação, segundo Goldemberg, não é válida nem para os Estados Unidos nem para o Brasil, os dois maiores produtores. Nos Estados Unidos, a matéria-
prima do álcool é milho, cujo cultivo avança sobre áreas de soja, e não sobre terras virgens (artigo raro por lá).

Aqui, as lavouras de cana ocupam superfície comparável à do Rio Grande do Norte, mas isso corresponde a meros 2% dos 2,9 milhões de km2 utilizados pelo setor
agropecuário. E o aumento da área canavieira, inegável, costuma ocorrer pela conversão de pastagens. Para o físico, a cana não contribui nem mesmo de modo
indireto para desmatar a Amazônia, pois o espaço ocupado por pastos está até diminuindo – é a produtividade da pecuária que aumenta.

O segundo equívoco Goldemberg descarta com outro dado objetivo: a agricultura de todos os países juntos se espalha por 12 milhões de km2 do planeta, mas só 100
mil km2 são destinados a biocombustíveis nos EUA e no Brasil. Ou seja, os “críticos perderam completamente o senso de proporção”.

O terceiro mito, do suposto balanço energético desfavorável dos biocombustíveis, é rebatido pelo entrevistado com uma condenação ao álcool de milho. Este produz
apenas 1,5 unidade de energia renovável para cada unidade de energia fóssil (petróleo empregado para produzir fertilizantes ou diesel para máquinas, por exemplo).
O álcool de cana, por seu turno, rende oito. Vale dizer, o etanol brasileiro é cinco vezes mais eficiente para substituir combustíveis que agravam o aquecimento
global.

Por fim, Goldemberg derruba a quarta mistificação, assinalando que apenas 25% da cana mundial está plantada no Brasil. Há canaviais em vários outros países
tropicais, como os da América Central e da África, para citar duas regiões com grande potencial de expansão.

(Folha de S.Paulo, 28.04.2008. Adaptado)

Em termos argumentativos, a comparação da área de plantio de cana com a área do Rio Grande do Norte (terceiro parágrafo) corresponde ao emprego de um recurso
de', 'revelação.', 'imposição.', 'reserva.', 'verificação.', 'ilustração.', 'A', 1, NULL);
INSERT IGNORE INTO questions (statement, option_a, option_b, option_c, option_d, option_e, correct_option, pdf_page_ref, owner_id) VALUES ('VUNESP - AJ (TJ MT)/TJ MT/Letras/2008

Língua Portuguesa (Português) - Tipologia e Gênero Textual

19) 

Leia o poema de Cecília Meireles para responder à questão.

Canção Mínima

No Mistério do Sem-Fim,
equilibra-se um planeta.
E, no planeta, um jardim,
e, no jardim, um canteiro;
no canteiro, uma violeta,
e, sobre ela, o dia inteiro,
entre o planeta e o Sem-Fim,
a asa de uma borboleta.

(Obra Poética, p. 163)

Esse poema foi inteiramente construído por meio de', 'citações.', 'argumentos.', 'inovações léxicas.', 'adjetivos.', 'elipses.', 'A', 1, NULL);
INSERT IGNORE INTO questions (statement, option_a, option_b, option_c, option_d, option_e, correct_option, pdf_page_ref, owner_id) VALUES ('VUNESP - Tec Leg(CM SP)/CM SP/"Sem Área"/2007

Língua Portuguesa (Português) - Tipologia e Gênero Textual

20) 

A despeito das controvérsias, o que efetivamente intriga os cientistas é o fato de nossos ancestrais terem, em certo momento da evolução, deixado de lado suas
preocupações básicas com comida, água, abrigo ou predadores para se dedicarem a fazer ornamentos e bibelôs.

Ao definir o que intriga os cientistas, o texto contrapõe', 'nossos ancestrais e evolução.', 'comida e predadores.', 'preocupações básicas e ornamentos e bibelôs.', 'deixar de lado e preocupações.', 'dedicarem e ornamentos.', 'A', 1, NULL);
INSERT IGNORE INTO questions (statement, option_a, option_b, option_c, option_d, option_e, correct_option, pdf_page_ref, owner_id) VALUES ('VUNESP - Cons Leg (CM SP)/CM SP/Contador/2007
Língua Portuguesa (Português) - Tipologia e Gênero Textual

21) 

O que aconteceria se o voto nulo ganhasse as eleições?

Guerra? Tumulto? Que nada: os votos nulos até podem melar eleições se chegarem a mais de 50% do total, só que a Lei Eleitoral exige um novo pleito. Deve rolar outra
votação entre 20 e 40 dias depois, com os mesmos candidatos. E isso vale tanto em eleições para o Executivo como para o Legislativo. Já, se os nulos chegarem na
frente sem passar dos 50%, não acontece nada. Num eventual 2.º turno, eles também não contam. Mesmo se um candidato levar por dois votos a um, está valendo – os
nulos acabam subtraídos do resultado final, do mesmo jeito que os votos em branco. A única diferença entre brancos e nulos, aliás, é justamente a chance de estes
últimos invalidarem a eleição. “Em tese, o branco significa aceitação, tipo: ‘Qualquer candidato está valendo.’ E o nulo é de quem diz ‘Nenhum candidato merece
meu voto’”, diz o cientista político Carlos Melo, da Faculdade Ibmec São Paulo. Nos tempos pré-urna eletrônica, quando os eleitores podiam escrever na cédula, os
descontentes tinham como mostrar quem “merecia” mesmo seus votos. Em 1958, por exemplo, o grande nome das eleições para vereador em São Paulo foi um
rinoceronte, o Cacareco. Ele já freqüentava as colunas sociais desde a inauguração do Zoológico de São Paulo, e entrou na política pelas mãos do então bairro de
Osasco, que brigava para se tornar uma cidade. O chifrudo ficou em 1.º, com 100 mil votos. No Rio, 30 anos depois, foi a vez de outro ilustre mamífero: o macaco
Tião. Lançada pela revista Casseta e Planeta, a candidatura do chimpanzé à prefeitura rendeu um imponente 3.º lugar – foram 400 mil votos, ou 9,5% do total.

(Raquel Cozer, Superinteressante, junho, 2006)

O texto, quanto à sua tipologia, é predominantemente', 'descritivo, pois explicita, figurativamente, características de pessoas e de situações.', 'expositivo, pois apresenta informações precisas acerca de um determinado assunto.', 'narrativo, pois enumera fatos vivenciados por personagens, numa seqüência temporal.', 'injuntivo, pois emprega expressões lingüísticas típicas da linguagem fática, para não interromper a comunicação.', 'dissertativo, pois desenvolve argumentação crítica a respeito de um fato, com exaustivos exemplos.', 'A', 1, NULL);
INSERT IGNORE INTO questions (statement, option_a, option_b, option_c, option_d, option_e, correct_option, pdf_page_ref, owner_id) VALUES ('VUNESP - Cons Leg (CM SP)/CM SP/Comunicação Social/Jornalismo/2007
Língua Portuguesa (Português) - Tipologia e Gênero Textual

22) 

A economia brasileira mudou de ritmo na passagem de 2006 para 2007. O crescimento econômico deve superar os 4% neste ano, com os mais otimistas falando em
números ainda maiores.

Grande parte dos analistas mantém esse quadro de crescimento mais acelerado para os próximos anos. Existe um clima de otimismo elevado entre os empresários, e a
decisão de realizar grandes investimentos domina as pesquisas realizadas por vários institutos.

Já apareceu na imprensa a expressão há tanto tempo esquecida do “espírito animal dos empresários” como a principal razão dessas mudanças.

Mas, afinal, o que mudou na economia para que, repentinamente, fosse deixado para trás o período de chumbo do baixo crescimento econômico que nos dominou a
todos durante mais de duas décadas? Os grandes obstáculos citados, por longos anos, por economistas da academia e do mercado não foram superados, pois a maioria
deles nem sequer foi enfrentada pelo governo Lula.

Cito alguns: o risco jurídico dos contratos, a elevada e ineficiente carga tributária e seu irmão gêmeo, que se chama crescimento dos gastos públicos, os déficits
crescentes da Previdência e o baixo investimento do governo na infra-estrutura econômica.

Para entender essa mudança inesperada, precisamos refletir sobre essas causas há tanto tempo apontadas como limitadoras de nosso crescimento. Hoje, podemos
dizer com segurança que elas não representavam os reais motivos durante todo esse tempo.

Apesar da importância que todas elas trazem para o desenvolvimento sadio de uma economia de mercado moderna, não eram elas que realmente limitavam nosso
crescimento.

(Luiz Carlos Mendonça de Barros. A volta do espírito animal. Folha de S.Paulo, 25.05.2007)

É correto afirmar que, no texto, predominam aspectos', 'dissertativo-argumentativos, revelados pela seleção, oposição e ilustração de idéias e pela exortação final.', 'narrativos, que se revelam no seqüenciamento de ações motivadas não só pelas personagens citadas, mas também pelas personagens envolvidas.', 'descritivos de caráter técnico-objetivo, revelados pelos dados estatísticos presentes no texto e pelos eventos correlacionados citados.', 'descritivos dinâmicos de caráter subjetivo, revelados pelo questionamento apresentado no segundo parágrafo e pelo uso recorrente da primeira pessoa do
plural.', 'descritivos estáticos, revelados especialmente pelos exemplos no final do segundo parágrafo e pela presença de verbos conjugados no tempo passado.', 'A', 1, NULL);
